### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by pbonte** [streamreasoning/rsp4j#6]
Pending tasks for RSP4J:

- [x] Task abstractions
- [x] Publication abstraction
- [ ] Mapping support
- [ ] RSP-QL query loading
- [ ] Window generalization
- [ ] Stateless functions (map, filter,..) 
- [ ] Remove observer pattern
- [ ] Write javadoc
- [ ] Update wiki
- [ ] Write Tests
